-- 根据数据表格严格按照表头顺序创建MySQL建表语句
-- 表名：全球通量质构效指标数据表

CREATE TABLE anaylsis_qqt_lzgx_st_mm (
    op_month bigint(20) NULL COMMENT "",

    city_name VARCHAR(50) NOT NULL COMMENT '地市',
    
    -- 全球通相关字段
    qqt_amt BIGINT COMMENT '全球通客户收入-万元',
    pzqqt_amt BIGINT COMMENT '拍照全球通客户收入-万元',
    qqt_cnt BIGINT COMMENT '全球通客户数-户',
    qqt_user_pka BIGINT COMMENT '全球通普卡客户数-户',
    qqt_user_yka BIGINT COMMENT '全球通银卡客户数-户',
    qqt_user_jka BIGINT COMMENT '全球通金卡客户数-户',
    qqt_user_bjka BIGINT COMMENT '全球通白金卡客户数-户',
    qqt_user_zska BIGINT COMMENT '全球通钻石卡客户数-户',
    qqt_user_zyzska BIGINT COMMENT '全球通卓越钻石卡客户数-户',
    qqt_jz BIGINT COMMENT '全球通客户拍照净增数-户',
    qqt_new BIGINT COMMENT '全球通客户当月新增数-户',
    qqt_cnt_online BIGINT COMMENT '拍照全球通在网客户数-户',
    qqt_cnt_lw BIGINT COMMENT '拍照全球通离网客户数-户',
    qqtzj BIGINT COMMENT '全球通组家客户数-户',
    qqtkd BIGINT COMMENT '全球通宽带客户数-户',
    qqtjt BIGINT COMMENT '全球通集团客户数-户',
    zd_online2yup BIGINT COMMENT '全球通长机龄客户数-户',
    pzqqt_gm BIGINT COMMENT '拍照全球通客户规模保有率-%',
    pzqqt_jz BIGINT COMMENT '拍照全球通客户收入保有率-%',
    pzqqt_zh BIGINT COMMENT '拍照全球通客户综合保有率-%',
    ydapp_hy BIGINT COMMENT '中国移动APP次月活跃率-%',
    gm_st BIGINT COMMENT '国漫渗透率-%',
    jc_10086_sy BIGINT COMMENT '10086专席使用率-%',
    jc_10086_wh BIGINT COMMENT '10086专席外呼率-%',
    dm_user_zb BIGINT COMMENT '低满用户占比-%',
    tsuser3mon_zb BIGINT COMMENT '投诉用户占比-%',
    ywtd_zb BIGINT COMMENT '业务退订用户占比-%',
    hdjx_zb BIGINT COMMENT '活动接续用户占比-%',
    gyrh_zb BIGINT COMMENT '全球通客户固移融合率-%',
    yxrh_zb BIGINT COMMENT '全球通客户有效融合率-%',
    ydkh_zb BIGINT COMMENT '全球通异动客户占比-%',
    old_zb BIGINT COMMENT '全球通银发用户占比-%',
    gjmy_zb BIGINT COMMENT '全球通国际用户占比-%',
    stu_zb BIGINT COMMENT '全球通校园用户占比-%',
    kuandai_1000 BIGINT COMMENT '宽带带宽1000MB的全球通用户数-户',
    kuandai_500 BIGINT COMMENT '宽带带宽500MB的全球通用户数-户',
    kuandai_300 BIGINT COMMENT '宽带带宽300MB的全球通用户数-户',
    kuandai_200 BIGINT COMMENT '宽带带宽200MB的全球通用户数-户',
    kuandai_100 BIGINT COMMENT '宽带带宽100MB的全球通用户数-户',
    kuandai_0_100 BIGINT COMMENT '宽带带宽100MB以下的全球通用户数-户',
    kuandai_none BIGINT COMMENT '无宽带全球通用户数-户',
    tarpu_fc_0 BIGINT COMMENT 'TARPU0元及以下全球通用户数-户',
    tarpu_fc_0_30 BIGINT COMMENT 'TARPU(0,30)元全球通用户数-户',
    tarpu_fc_0_50 BIGINT COMMENT 'TARPU[30,50)元全球通用户数-户',
    tarpu_fc_50_100 BIGINT COMMENT 'TARPU[50,100)元全球通用户数-户',
    tarpu_fc_100_150 BIGINT COMMENT 'TARPU[100,150)元全球通用户数-户',
    tarpu_fc_150_200 BIGINT COMMENT 'TARPU[150,200)元全球通用户数-户',
    tarpu_fc_200_300 BIGINT COMMENT 'TARPU[200,300)元全球通用户数-户',
    tarpu_fc_300 BIGINT COMMENT 'TARPU300元以上全球通用户数-户',
    dou_fc_0 BIGINT COMMENT 'DOU0GB全球通用户数-户',
    dou_fc_0_1 BIGINT COMMENT 'DOU(0,1)GB全球通用户数-户',
    dou_fc_1_5 BIGINT COMMENT 'DOU[1,5)GB全球通用户数-户',
    dou_fc_5_10 BIGINT COMMENT 'DOU[5,10)GB全球通用户数-户',
    dou_fc_15_20 BIGINT COMMENT 'DOU[10,20)GB全球通用户数-户',
    dou_fc_20_30 BIGINT COMMENT 'DOU[20,30)GB全球通用户数-户',
    dou_fc_30_50 BIGINT COMMENT 'DOU[30,50)GB全球通用户数-户',
    dou_fc_50_100 BIGINT COMMENT 'DOU[50,100)GB全球通用户数-户',
    dou_fc_100_200 BIGINT COMMENT 'DOU[100,200)GB全球通用户数-户',
    dou_fc_200 BIGINT COMMENT 'DOU200GB以上全球通用户数-户',
    online_fc_0_1 BIGINT COMMENT '网龄[0,1)年全球通用户数-户',
    online_fc_1_5 BIGINT COMMENT '网龄[1,5)年全球通用户数-户',
    online_fc_5_10 BIGINT COMMENT '网龄[5,10)年全球通用户数-户',
    online_fc_10_15 BIGINT COMMENT '网龄[10,15)年全球通用户数-户',
    online_fc_15_20 BIGINT COMMENT '网龄[15,20)年全球通用户数-户',
    online_fc_20_30 BIGINT COMMENT '网龄[20,30)年全球通用户数-户',
    online_fc_30 BIGINT COMMENT '网龄30年以上全球通用户数-户',
    tarpu_dwn_cnt BIGINT COMMENT '价值下降全球通客户数-户',
    tarpu_dwn_amt BIGINT COMMENT '价值下降全球通客户下降总价值-元',
    tarpu_up_cnt BIGINT COMMENT '价值提升全球通客户数-户',
    tarpu_up_amt BIGINT COMMENT '价值提升全球通客户下降总价值-元',
    hyyh_cnt BIGINT COMMENT '合约全球通客户-户',
    plan_dwn_cnt BIGINT COMMENT '套餐降档全球通客户-户',
    pzqqt_tarpu BIGINT COMMENT '拍照全球通客户TARPU-元',
    pzqqt_dou BIGINT COMMENT '拍照全球通客户DOU-GB',
    pzqqt_bhd BIGINT COMMENT '拍照全球通客户通用包月流量饱和度-%',
    pzqqt_mou_zj BIGINT COMMENT '拍照全球通客户主叫MOU-分钟',
    qqt_tarpu BIGINT COMMENT '到达全球通客户TARPU-元',
    qqt_dou BIGINT COMMENT '到达全球通客户DOU-GB',
    qqt_bhd BIGINT COMMENT '到达全球通客户通用包月流量饱和度-%',
    qqt_mou_zj BIGINT COMMENT '到达全球通客户主叫MOU-分钟',
    xdr_usercnt BIGINT COMMENT '星动日活动参与客户数-户',
    qylq_usercnt BIGINT COMMENT '权益领取客户数-户',
    ajwlqqt_usercnt BIGINT COMMENT '三大行动参与客户数-户',
    
    billing_customers BIGINT COMMENT '出账客户-户',
    communication_customers BIGINT COMMENT '通信客户-户', 
    mobile_internet_customers BIGINT COMMENT '手机上网客户-户',
    g5_terminal_customers BIGINT COMMENT '5G终端客户-户',
    g5_network_customers BIGINT COMMENT '5G登网客户-户',
    traffic_exceed_customers BIGINT COMMENT '流量超套客户-户',
    traffic_exceed_avg_fee BIGINT COMMENT '流量超套客户户均超套费-元',
    voice_exceed_customers BIGINT COMMENT '语音超套客户-户',
    voice_exceed_avg_fee BIGINT COMMENT '语音超套客户户均超套费-元',
    photo_global_portout_customers BIGINT COMMENT '拍照全球通携出客户-户',
    photo_global_cancel_customers BIGINT COMMENT '拍照全球通申销客户-户',
    photo_global_arrears_customers BIGINT COMMENT '拍照全球通欠销客户-户',
    roaming_penetration_rate BIGINT COMMENT '常漫客户（省际漫游）渗透率-%',
    arrears_ratio BIGINT COMMENT '欠费客户占比-%',
    contact_10088_ratio BIGINT COMMENT '10088接触客户占比-%',
    contract_customers_valid BIGINT COMMENT '合约客户（有效融合口径）-户',
    terminal_contract_customers BIGINT COMMENT '终端合约客户',
    package_upgrade_customers BIGINT COMMENT '套餐升档客户-户',
    package_fee_avg BIGINT COMMENT '套餐费实收费均值-元',
    
    -- 套餐费实收各档位
    package_fee_0 BIGINT COMMENT '套餐费实收-0元',
    package_fee_0_10 BIGINT COMMENT '套餐费实收-(0,10)元',
    package_fee_10_30 BIGINT COMMENT '套餐费实收-(10,30)元', 
    package_fee_30_50 BIGINT COMMENT '套餐费实收-[30,50)元',
    package_fee_50_80 BIGINT COMMENT '套餐费实收-[50,80)元',
    package_fee_80_108 BIGINT COMMENT '套餐费实收-[80,108)元',
    package_fee_108_150 BIGINT COMMENT '套餐费实收-[108,150)元',
    package_fee_150_200 BIGINT COMMENT '套餐费实收-[150,200)元',
    package_fee_200_300 BIGINT COMMENT '套餐费实收-[200,300)元',
    package_fee_300_above BIGINT COMMENT '套餐费实收-300元以上',
    
    -- 时间戳
    op_month INT COMMENT '操作月份',
    created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    
    -- 索引
    INDEX idx_city_month (city_name, op_month),
    INDEX idx_op_month (op_month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='全球通量质构效指标数据表';
